@startuml

title Compute Total 

participant User
participant Company
participant Department
participant Position
participant Employee

activate User
User -> Company: 1. getSalary()
activate Company
    Company -> Department: 2. *getSalary()
    activate Department
        Department -> Position: 3. *getSalary()
        activate Position
            Position -> Employee: 4. getSalary()
            activate Employee
            deactivate Employee
        deactivate Position
    deactivate Department
deactivate Company
deactivate User

@enduml
